

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shri
 */
public class AddCourse extends javax.swing.JFrame {

    /**
     * Creates new form AddCourse
     */
    
    course c=new course();
    public AddCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelac = new javax.swing.JLabel();
        jLabelchrs = new javax.swing.JLabel();
        jLabelAddlabl = new javax.swing.JLabel();
        jTextFieldlabel = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jButtonacadd = new javax.swing.JButton();
        jButtonacrem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 51), 2, true));

        jLabelac.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabelac.setForeground(new java.awt.Color(0, 135, 28));
        jLabelac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelac.setText("Add Course");

        jLabelchrs.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelchrs.setForeground(new java.awt.Color(49, 16, 221));
        jLabelchrs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelchrs.setText("Hours  :");

        jLabelAddlabl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelAddlabl.setForeground(new java.awt.Color(49, 23, 224));
        jLabelAddlabl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAddlabl.setText("Label :");

        jTextFieldlabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jSpinner1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));

        jButtonacadd.setBackground(new java.awt.Color(255, 218, 40));
        jButtonacadd.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonacadd.setForeground(new java.awt.Color(255, 51, 0));
        jButtonacadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addcourse.png"))); // NOI18N
        jButtonacadd.setText("ADD");
        jButtonacadd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 2, true));
        jButtonacadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonacaddActionPerformed(evt);
            }
        });

        jButtonacrem.setBackground(new java.awt.Color(255, 218, 40));
        jButtonacrem.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonacrem.setForeground(new java.awt.Color(255, 51, 0));
        jButtonacrem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelac.png"))); // NOI18N
        jButtonacrem.setText("CANCEL");
        jButtonacrem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 2, true));
        jButtonacrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonacremActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabelac, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelAddlabl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelchrs, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonacadd, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonacrem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelAddlabl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelchrs)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonacadd)
                    .addComponent(jButtonacrem))
                .addGap(137, 137, 137))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonacremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonacremActionPerformed
     
        this.dispose();
    }//GEN-LAST:event_jButtonacremActionPerformed

    
    
    private void jButtonacaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonacaddActionPerformed
    
       String label=jTextFieldlabel.getText();
       int hours=Integer.valueOf(jSpinner1.getValue().toString());
       
       if(label.equals("")|| hours<=0){
           JOptionPane.showMessageDialog(null,"Please Give the Label !");
       }
       else if(!c.isCourseExist(label)){
           c.insertUpdateDeleteCourse('i',null, label, hours);
           MainForm.jLabelcoursecount.setText("Course Count : "+Integer.toString(MyFunction.countData("course")));
     
           MainForm.jLabelcoursecount.setText("Course Count : "+Integer.toString(MyFunction.countData("course")));
           try{
             ManageCourseForm.jTablecourse.setModel(new DefaultTableModel(null,new Object[]{"Id","Label","Hours"})); 
             c.fillCourseJtable(ManageCourseForm.jTablecourse);
           }
            catch(Exception e){
                    System.out.println(e.getMessage());
                    }
       }
       else{
           JOptionPane.showMessageDialog(null,"Course Alredy Exists");
       }
        
    
        
    }//GEN-LAST:event_jButtonacaddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonacadd;
    private javax.swing.JButton jButtonacrem;
    private javax.swing.JLabel jLabelAddlabl;
    private javax.swing.JLabel jLabelac;
    private javax.swing.JLabel jLabelchrs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextFieldlabel;
    // End of variables declaration//GEN-END:variables
}
