

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shri
 */
public class addScoreForm extends javax.swing.JFrame {

    /**
     * Creates new form addScoreForm
     */
    course c=new course();
    student s=new student();
    score sc=new score();
    
    
    DefaultTableModel model;
    public addScoreForm() {
        initComponents();
        c.fillCourseCombo(jComboBoxcrsid);
        s.fillStudentJtable(jTablescrstd,"");
        
        HideColumn(6);
        HideColumn(5);
        HideColumn(4);
        HideColumn(3);
        
         model=(DefaultTableModel) jTablescrstd.getModel();
        jTablescrstd.setRowHeight(30);
        jTablescrstd.setShowGrid(true);
        jTablescrstd.setGridColor(Color.black);
        jTablescrstd.setSelectionForeground(Color.black);
        jTablescrstd.setSelectionBackground(Color.lightGray);
    }
    private void HideColumn(int colIndex){
        TableColumn col=jTablescrstd.getColumnModel().getColumn(colIndex);
        col.setMaxWidth(0);
        col.setMinWidth(0);
        col.setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeladdscore = new javax.swing.JLabel();
        jLabelscore = new javax.swing.JLabel();
        jLabelcrsid = new javax.swing.JLabel();
        jButtonamgcadd = new javax.swing.JButton();
        jButtonmgacrem = new javax.swing.JButton();
        jLabelstdid = new javax.swing.JLabel();
        jTextFieldstdid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablescrstd = new javax.swing.JTable();
        jTextFieldscore = new javax.swing.JTextField();
        jComboBoxcrsid = new javax.swing.JComboBox();
        jLabeldscrp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 51), 2, true));

        jLabeladdscore.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabeladdscore.setForeground(new java.awt.Color(255, 51, 0));
        jLabeladdscore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeladdscore.setText("Add Score");

        jLabelscore.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelscore.setForeground(new java.awt.Color(49, 16, 221));
        jLabelscore.setText("Score :");

        jLabelcrsid.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelcrsid.setForeground(new java.awt.Color(49, 23, 224));
        jLabelcrsid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcrsid.setText("Course Id :");

        jButtonamgcadd.setBackground(new java.awt.Color(255, 218, 40));
        jButtonamgcadd.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonamgcadd.setForeground(new java.awt.Color(255, 51, 0));
        jButtonamgcadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addcourse.png"))); // NOI18N
        jButtonamgcadd.setText("ADD");
        jButtonamgcadd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 2, true));
        jButtonamgcadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonamgcaddActionPerformed(evt);
            }
        });

        jButtonmgacrem.setBackground(new java.awt.Color(255, 218, 40));
        jButtonmgacrem.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonmgacrem.setForeground(new java.awt.Color(255, 51, 0));
        jButtonmgacrem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jButtonmgacrem.setText("CANCEL");
        jButtonmgacrem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 2, true));
        jButtonmgacrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmgacremActionPerformed(evt);
            }
        });

        jLabelstdid.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelstdid.setForeground(new java.awt.Color(49, 23, 224));
        jLabelstdid.setText("Student Id :");

        jTextFieldstdid.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 102), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTablescrstd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Last Name", "Gender", "BirthDate", "Phone", "Address"
            }
        ));
        jTablescrstd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablescrstdMouseClicked(evt);
            }
        });
        jTablescrstd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablescrstdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTablescrstdKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTablescrstd);

        jTextFieldscore.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldscoreActionPerformed(evt);
            }
        });

        jComboBoxcrsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxcrsidActionPerformed(evt);
            }
        });

        jLabeldscrp.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabeldscrp.setForeground(new java.awt.Color(49, 23, 224));
        jLabeldscrp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeldscrp.setText("Description :");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelstdid, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldstdid, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelcrsid)
                                    .addGap(22, 22, 22)
                                    .addComponent(jComboBoxcrsid, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelscore, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldscore, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabeldscrp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButtonmgacrem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonamgcadd, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabeladdscore, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabeladdscore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelstdid)
                            .addComponent(jTextFieldstdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jComboBoxcrsid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelcrsid))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelscore)
                            .addComponent(jTextFieldscore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeldscrp)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonmgacrem, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonamgcadd))
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonamgcaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonamgcaddActionPerformed
       int stdId=Integer.valueOf(jTextFieldstdid.getText());
       int crsId=Integer.valueOf(c.getCourseId(jComboBoxcrsid.getSelectedItem().toString()));
       double scr=Double.valueOf(jTextFieldscore.getText());
       
       sc.insertUpdateDeleteScore('i', stdId, crsId,scr,jTextArea1.getText());
try{updateScore.jTablescores.setModel(new DefaultTableModel(null,new Object[]{"StduentID","CourseID","Score","Description"})); 
       sc.fillScoreJtable(updateScore.jTablescores,"");}
catch(Exception e){
System.out.println(e.getMessage());
}
       
//        AddCourse adc=new AddCourse();
//        adc.setVisible(true);
//        adc.pack();
//        adc.setLocationRelativeTo(null);
//        adc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButtonamgcaddActionPerformed

    private void jButtonmgacremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmgacremActionPerformed
        this.dispose();

//        String label=jTextFieldcrsid.getText();
//        int id=Integer.valueOf(jTextFieldstdid.getText());
//        int hours=(int) jSpinner1.getValue();
//
//        course c=new course();
//        c.insertUpdateDeleteCourse('d', id, label, hours);
//        MainForm.jLabelcoursecount.setText("Course Count : "+Integer.toString(MyFunction.countData("course")));
//
//        ManageCourseForm.jTablecourse.setModel(new DefaultTableModel(null,new Object[]{"Id","Label","Hours"}));
//        c.fillCourseJtable(jTablecourse);

        //        this.dispose();
    }//GEN-LAST:event_jButtonmgacremActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       addScoreForm mcf=new  addScoreForm();
        this.dispose();
        mcf.setVisible(true);
        mcf.pack();
        mcf.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTablescrstdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablescrstdMouseClicked
        int rowIndex=jTablescrstd.getSelectedRow();
        jTextFieldstdid.setText(jTablescrstd.getValueAt(rowIndex,0).toString());
        

//        
//        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
//        if(model.getValueAt(rowIndex,3).toString().equals("Male")){
//            jRadioButtomgnm.setSelected(true);
//            jRadioButtonmgf.setSelected(false);
//        }
//        else{
//            jRadioButtomgnm.setSelected(false);
//            jRadioButtonmgf.setSelected(true);
//        }
//        jTextFieldID.setText(model.getValueAt(rowIndex,0).toString());
//        jTextFieldmgfn.setText(model.getValueAt(rowIndex,1).toString());
//        jTextFieldmgln.setText(model.getValueAt(rowIndex,2).toString());
//        jTextFieldmgbd.setText(model.getValueAt(rowIndex,4).toString());
//        jTextFieldmgphone.setText(model.getValueAt(rowIndex,5).toString());
//        jTextAreamgadd.setText(model.getValueAt(rowIndex,6).toString());

    }//GEN-LAST:event_jTablescrstdMouseClicked

    private void jTablescrstdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablescrstdKeyPressed
        if(evt.getKeyCode()==10){
            evt.consume();
        }
    }//GEN-LAST:event_jTablescrstdKeyPressed

    private void jTablescrstdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablescrstdKeyReleased
//        if(evt.getKeyCode()==10){
//            int rowIndex=jTable1.getSelectedRow();
//            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
//            if(model.getValueAt(rowIndex,3).toString().equals("Male")){
//                jRadioButtomgnm.setSelected(true);
//                jRadioButtonmgf.setSelected(false);
//            }
//            else{
//                jRadioButtomgnm.setSelected(false);
//                jRadioButtonmgf.setSelected(true);
//            }
//            jTextFieldID.setText(model.getValueAt(rowIndex,0).toString());
//            jTextFieldmgfn.setText(model.getValueAt(rowIndex,1).toString());
//            jTextFieldmgln.setText(model.getValueAt(rowIndex,2).toString());
//            jTextFieldmgbd.setText(model.getValueAt(rowIndex,4).toString());
//            jTextFieldmgphone.setText(model.getValueAt(rowIndex,5).toString());
//            jTextAreamgadd.setText(model.getValueAt(rowIndex,6).toString());
//
//        }

    }//GEN-LAST:event_jTablescrstdKeyReleased

    private void jTextFieldscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldscoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldscoreActionPerformed

    private void jComboBoxcrsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxcrsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxcrsidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addScoreForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonamgcadd;
    private javax.swing.JButton jButtonmgacrem;
    private javax.swing.JComboBox<String> jComboBoxcrsid;
    private javax.swing.JLabel jLabeladdscore;
    private javax.swing.JLabel jLabelcrsid;
    private javax.swing.JLabel jLabeldscrp;
    private javax.swing.JLabel jLabelscore;
    private javax.swing.JLabel jLabelstdid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jTablescrstd;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldscore;
    private javax.swing.JTextField jTextFieldstdid;
    // End of variables declaration//GEN-END:variables
}
