

import java.io.Console;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shri
 */
public class Addstudent extends javax.swing.JFrame {

    /**
     * Creates new form Addstudent
     */
    
    student std=new student();
    
    public Addstudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelfn = new javax.swing.JLabel();
        jLabelln = new javax.swing.JLabel();
        jLabelgender = new javax.swing.JLabel();
        jLabelbd = new javax.swing.JLabel();
        jLabelphone = new javax.swing.JLabel();
        jLabeladd = new javax.swing.JLabel();
        jTextFieldfn = new javax.swing.JTextField();
        jTextFieldln = new javax.swing.JTextField();
        jRadioButtonm = new javax.swing.JRadioButton();
        jRadioButtonf = new javax.swing.JRadioButton();
        jTextFieldbd = new javax.swing.JTextField();
        jTextFieldphone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaadd = new javax.swing.JTextArea();
        jButtonadd = new javax.swing.JButton();
        jButtonadd1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Student");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(175, 245, 242));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Student");

        jLabelfn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelfn.setForeground(new java.awt.Color(49, 23, 224));
        jLabelfn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelfn.setText("First Name :");

        jLabelln.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelln.setForeground(new java.awt.Color(49, 16, 221));
        jLabelln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelln.setText("Last Name :");

        jLabelgender.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelgender.setForeground(new java.awt.Color(49, 29, 196));
        jLabelgender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelgender.setText("Gender :");

        jLabelbd.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelbd.setForeground(new java.awt.Color(49, 29, 196));
        jLabelbd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelbd.setText("BirthDate :");

        jLabelphone.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelphone.setForeground(new java.awt.Color(49, 29, 196));
        jLabelphone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelphone.setText("Phone :");

        jLabeladd.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabeladd.setForeground(new java.awt.Color(49, 29, 196));
        jLabeladd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeladd.setText("Address :");

        jTextFieldfn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jTextFieldln.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        buttonGroup1.add(jRadioButtonm);
        jRadioButtonm.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jRadioButtonm.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButtonm.setText("Male");

        buttonGroup1.add(jRadioButtonf);
        jRadioButtonf.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jRadioButtonf.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButtonf.setSelected(true);
        jRadioButtonf.setText("Female");

        jTextFieldbd.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldbd.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldbd.setText("dd-mm-yyyy");
        jTextFieldbd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldbdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldbdFocusLost(evt);
            }
        });
        jTextFieldbd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldbdKeyTyped(evt);
            }
        });

        jTextFieldphone.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldphone.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldphoneActionPerformed(evt);
            }
        });
        jTextFieldphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldphoneKeyTyped(evt);
            }
        });

        jTextAreaadd.setColumns(20);
        jTextAreaadd.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextAreaadd.setRows(5);
        jScrollPane1.setViewportView(jTextAreaadd);

        jButtonadd.setBackground(new java.awt.Color(51, 153, 255));
        jButtonadd.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonadd.setForeground(new java.awt.Color(153, 0, 204));
        jButtonadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButtonadd.setText("ADD");
        jButtonadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddActionPerformed(evt);
            }
        });

        jButtonadd1.setBackground(new java.awt.Color(51, 153, 255));
        jButtonadd1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonadd1.setForeground(new java.awt.Color(153, 0, 204));
        jButtonadd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButtonadd1.setText("CANCEL");
        jButtonadd1.setToolTipText("");
        jButtonadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonadd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelfn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelln)
                            .addComponent(jLabelgender)
                            .addComponent(jLabelbd)
                            .addComponent(jLabelphone)
                            .addComponent(jLabeladd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldphone, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(jTextFieldbd, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonm, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jRadioButtonf, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(jTextFieldln)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jTextFieldfn, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButtonadd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabelfn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldfn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelln, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldln, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelgender)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonm)
                                .addComponent(jRadioButtonf)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelbd)
                            .addComponent(jTextFieldbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabelphone))
                    .addComponent(jTextFieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeladd)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonadd)
                    .addComponent(jButtonadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
      
        String fname=jTextFieldfn.getText();
        String lname=jTextFieldln.getText();
        String bdate=jTextFieldbd.getText();
        String phone=jTextFieldphone.getText();
        String address=jTextAreaadd.getText();
        String gender="Female";
        if(jRadioButtonm.isSelected()){
           gender="Male";
        }
        if(fname.equals("")||lname.equals("")|| bdate.equals("")||phone.equals("")||address.equals("")){
            JOptionPane.showMessageDialog(null, "Please Fill All Information !","Incompletet Data Error",2);
    }
        else{
            student stu=new student();
            stu.insertUpdateDeleteStudent('i', null, fname, lname, gender, bdate, phone, address);
            MainForm.jLabelstdcount.setText("Student Count : "+Integer.toString(MyFunction.countData("student")));
               
           ManageStudentForm.jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","First Name","Last Name","Gender","BirthDate","Phone","Address"})); 
           std.fillStudentJtable(ManageStudentForm.jTable1,"");
        }
    }//GEN-LAST:event_jButtonaddActionPerformed

    private void jButtonadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonadd1ActionPerformed
      this.dispose();
      
    }//GEN-LAST:event_jButtonadd1ActionPerformed

    private void jTextFieldphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldphoneKeyTyped
       if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
       }
    }//GEN-LAST:event_jTextFieldphoneKeyTyped

    private void jTextFieldbdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldbdFocusGained
    if(jTextFieldbd.getText().equals("dd-mm-yyyy")){
        jTextFieldbd.setText("");
    }
    }//GEN-LAST:event_jTextFieldbdFocusGained

    private void jTextFieldbdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldbdFocusLost
      if(jTextFieldbd.getText().equals("")){
        jTextFieldbd.setText("dd-mm-yyyy");
    }
    }//GEN-LAST:event_jTextFieldbdFocusLost

    private void jTextFieldbdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldbdKeyTyped
      if(!(Character.isDigit(evt.getKeyChar())|| evt.getKeyChar()=='-')){
           evt.consume();
       }
    }//GEN-LAST:event_jTextFieldbdKeyTyped

    private void jTextFieldphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldphoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonadd;
    private javax.swing.JButton jButtonadd1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabeladd;
    private javax.swing.JLabel jLabelbd;
    private javax.swing.JLabel jLabelfn;
    private javax.swing.JLabel jLabelgender;
    private javax.swing.JLabel jLabelln;
    private javax.swing.JLabel jLabelphone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonf;
    private javax.swing.JRadioButton jRadioButtonm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaadd;
    private javax.swing.JTextField jTextFieldbd;
    private javax.swing.JTextField jTextFieldfn;
    private javax.swing.JTextField jTextFieldln;
    private javax.swing.JTextField jTextFieldphone;
    // End of variables declaration//GEN-END:variables
}
