
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shri
 */
public class ManageCourseForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageCourseForm
     */
    
    course c=new course();
    
    public ManageCourseForm() {
        initComponents();
        
        c.fillCourseJtable(jTablecourse);
        jTablecourse.setRowHeight(30);
        jTablecourse.setShowGrid(true);
        jTablecourse.setGridColor(Color.black);
        jTablecourse.setSelectionBackground(Color.CYAN);
        jTablecourse.setSelectionForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelmgac = new javax.swing.JLabel();
        jLabelngchrs = new javax.swing.JLabel();
        jLabelmgAddlabl = new javax.swing.JLabel();
        jTextFieldmclabel = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jButtonamgcadd = new javax.swing.JButton();
        jButtonmgacrem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablecourse = new javax.swing.JTable();
        jButtonamgcedit = new javax.swing.JButton();
        jLabelmgid = new javax.swing.JLabel();
        jTextFieldmgid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 51), 2, true));

        jLabelmgac.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabelmgac.setForeground(new java.awt.Color(0, 135, 28));
        jLabelmgac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmgac.setText("Manage Course");

        jLabelngchrs.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelngchrs.setForeground(new java.awt.Color(49, 16, 221));
        jLabelngchrs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelngchrs.setText("Hours  :");

        jLabelmgAddlabl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelmgAddlabl.setForeground(new java.awt.Color(49, 23, 224));
        jLabelmgAddlabl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmgAddlabl.setText("Label :");

        jTextFieldmclabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jSpinner1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));

        jButtonamgcadd.setBackground(new java.awt.Color(255, 218, 40));
        jButtonamgcadd.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonamgcadd.setForeground(new java.awt.Color(255, 51, 0));
        jButtonamgcadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addcourse.png"))); // NOI18N
        jButtonamgcadd.setText("ADD");
        jButtonamgcadd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 2, true));
        jButtonamgcadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonamgcaddActionPerformed(evt);
            }
        });

        jButtonmgacrem.setBackground(new java.awt.Color(255, 218, 40));
        jButtonmgacrem.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonmgacrem.setForeground(new java.awt.Color(255, 51, 0));
        jButtonmgacrem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButtonmgacrem.setText("Remove");
        jButtonmgacrem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 2, true));
        jButtonmgacrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmgacremActionPerformed(evt);
            }
        });

        jTablecourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Label", "Hours"
            }
        ));
        jTablecourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablecourseMouseClicked(evt);
            }
        });
        jTablecourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablecourseKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTablecourseKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTablecourse);

        jButtonamgcedit.setBackground(new java.awt.Color(255, 218, 40));
        jButtonamgcedit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonamgcedit.setForeground(new java.awt.Color(255, 51, 0));
        jButtonamgcedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editcourse.png"))); // NOI18N
        jButtonamgcedit.setText("EDIT");
        jButtonamgcedit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 2, true));
        jButtonamgcedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonamgceditActionPerformed(evt);
            }
        });

        jLabelmgid.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelmgid.setForeground(new java.awt.Color(49, 23, 224));
        jLabelmgid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmgid.setText("ID :");

        jTextFieldmgid.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 102), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelmgAddlabl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldmclabel))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelmgid, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldmgid, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jLabelngchrs, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonamgcadd, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonmgacrem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonamgcedit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabelmgac, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelmgac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelmgid)
                            .addComponent(jTextFieldmgid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldmclabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelmgAddlabl))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelngchrs)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(179, 179, 179)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonamgcadd)
                            .addComponent(jButtonmgacrem, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonamgcedit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonamgcaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonamgcaddActionPerformed
    AddCourse adc=new AddCourse();
    adc.setVisible(true);
    adc.pack();
    adc.setLocationRelativeTo(null);
    adc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
     

    }//GEN-LAST:event_jButtonamgcaddActionPerformed

    private void jButtonmgacremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmgacremActionPerformed
/*
        ALTER TABLE score 
        ADD CONSTRAINT FK_score_course 
        FOREIGN KEY(course_id) 
        REFERENCES course(id) on DELETE CASCADE;
        */
        
        
        String label=jTextFieldmclabel.getText();
       int id=Integer.valueOf(jTextFieldmgid.getText());
       int hours=(int) jSpinner1.getValue();
      
           course c=new course();
            c.insertUpdateDeleteCourse('d', id, label, hours);
            MainForm.jLabelcoursecount.setText("Course Count : "+Integer.toString(MyFunction.countData("course")));

            try{ManageCourseForm.jTablecourse.setModel(new DefaultTableModel(null,new Object[]{"Id","Label","Hours"})); 
             c.fillCourseJtable(jTablecourse);}
catch(Exception e){
System.out.println(e.getMessage());
}
             
       
            
        
//        this.dispose();
    }//GEN-LAST:event_jButtonmgacremActionPerformed

    private void jButtonamgceditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonamgceditActionPerformed
       String label=jTextFieldmclabel.getText();
       int id=Integer.valueOf(jTextFieldmgid.getText());
       int hours=(int) jSpinner1.getValue();
       
            course c=new course();
            c.insertUpdateDeleteCourse('u', id, label, hours);
            MainForm.jLabelcoursecount.setText("Course Count : "+Integer.toString(MyFunction.countData("course")));

            try{ManageCourseForm.jTablecourse.setModel(new DefaultTableModel(null,new Object[]{"Id","Label","Hours"})); 
             c.fillCourseJtable(jTablecourse);}
catch(Exception e){
System.out.println(e.getMessage());
}
            
             
    }//GEN-LAST:event_jButtonamgceditActionPerformed

    private void jTablecourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablecourseMouseClicked
      int rowIndex=jTablecourse.getSelectedRow();
      DefaultTableModel model=(DefaultTableModel) jTablecourse.getModel();
    
      jTextFieldmgid.setText(model.getValueAt(rowIndex,0).toString());
      
      jTextFieldmclabel.setText(model.getValueAt(rowIndex,1).toString());
      jSpinner1.setValue(model.getValueAt(rowIndex,2));
     
      
    }//GEN-LAST:event_jTablecourseMouseClicked

    private void jTablecourseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablecourseKeyPressed
     if(evt.getKeyCode()==10){
    evt.consume();
}  
    }//GEN-LAST:event_jTablecourseKeyPressed

    private void jTablecourseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablecourseKeyReleased
     if(evt.getKeyCode()==10){
           
        int rowIndex=jTablecourse.getSelectedRow();
      DefaultTableModel model=(DefaultTableModel) jTablecourse.getModel();
    
      jTextFieldmgid.setText(model.getValueAt(rowIndex,0).toString());
      
      jTextFieldmclabel.setText(model.getValueAt(rowIndex,1).toString());
      jSpinner1.setValue(model.getValueAt(rowIndex,2));
        
       
    }  
    }//GEN-LAST:event_jTablecourseKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManageCourseForm mcf=new ManageCourseForm();
        this.dispose();
        mcf.setVisible(true);
        mcf.pack();
        mcf.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton1ActionPerformed

 

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCourseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonamgcadd;
    private javax.swing.JButton jButtonamgcedit;
    private javax.swing.JButton jButtonmgacrem;
    private javax.swing.JLabel jLabelmgAddlabl;
    private javax.swing.JLabel jLabelmgac;
    private javax.swing.JLabel jLabelmgid;
    private javax.swing.JLabel jLabelngchrs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    public static javax.swing.JTable jTablecourse;
    private javax.swing.JTextField jTextFieldmclabel;
    private javax.swing.JTextField jTextFieldmgid;
    // End of variables declaration//GEN-END:variables
}
