
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shri
 */
public class ManageStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudentForm
     */
     
    ButtonGroup bg=new ButtonGroup();
    student std=new student();
    
    DefaultTableModel model;
    public ManageStudentForm() {
        initComponents();
        std.fillStudentJtable(jTable1, "");
        bg.add(jRadioButtomgnm);
        bg.add(jRadioButtonmgf);
        
        model=(DefaultTableModel) jTable1.getModel();
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.black);
        jTable1.setSelectionForeground(Color.black);
        jTable1.setSelectionBackground(new Color(113,235,166));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelsearch = new javax.swing.JLabel();
        jLabelmgln = new javax.swing.JLabel();
        jLabelmggender = new javax.swing.JLabel();
        jLabelmgbd = new javax.swing.JLabel();
        jLabelmgphone = new javax.swing.JLabel();
        jLabelmgadd = new javax.swing.JLabel();
        jTextFieldmgfn = new javax.swing.JTextField();
        jTextFieldmgln = new javax.swing.JTextField();
        jRadioButtomgnm = new javax.swing.JRadioButton();
        jRadioButtonmgf = new javax.swing.JRadioButton();
        jTextFieldmgbd = new javax.swing.JTextField();
        jTextFieldmgphone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreamgadd = new javax.swing.JTextArea();
        jButtonmgedit = new javax.swing.JButton();
        jButtonmgrem = new javax.swing.JButton();
        jLabelmgfn = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jButtonmgadd1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldsearch = new javax.swing.JTextField();
        jLabelid1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(175, 245, 242));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage  Student");

        jLabelsearch.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelsearch.setForeground(new java.awt.Color(49, 23, 224));
        jLabelsearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelsearch.setText("Enter value to search :");

        jLabelmgln.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelmgln.setForeground(new java.awt.Color(49, 16, 221));
        jLabelmgln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmgln.setText("Last Name :");

        jLabelmggender.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelmggender.setForeground(new java.awt.Color(49, 29, 196));
        jLabelmggender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmggender.setText("Gender :");

        jLabelmgbd.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelmgbd.setForeground(new java.awt.Color(49, 29, 196));
        jLabelmgbd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmgbd.setText("BirthDate :");

        jLabelmgphone.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelmgphone.setForeground(new java.awt.Color(49, 29, 196));
        jLabelmgphone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmgphone.setText("Phone :");

        jLabelmgadd.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelmgadd.setForeground(new java.awt.Color(49, 29, 196));
        jLabelmgadd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmgadd.setText("Address :");

        jTextFieldmgfn.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jTextFieldmgln.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldmgln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmglnActionPerformed(evt);
            }
        });

        jRadioButtomgnm.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jRadioButtomgnm.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButtomgnm.setText("Male");

        jRadioButtonmgf.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jRadioButtonmgf.setForeground(new java.awt.Color(0, 51, 255));
        jRadioButtonmgf.setSelected(true);
        jRadioButtonmgf.setText("Female");
        jRadioButtonmgf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonmgfActionPerformed(evt);
            }
        });

        jTextFieldmgbd.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldmgbd.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldmgbd.setText("dd-mm-yyyy");
        jTextFieldmgbd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldmgbdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldmgbdFocusLost(evt);
            }
        });
        jTextFieldmgbd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldmgbdKeyTyped(evt);
            }
        });

        jTextFieldmgphone.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldmgphone.setForeground(new java.awt.Color(51, 102, 255));
        jTextFieldmgphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmgphoneActionPerformed(evt);
            }
        });
        jTextFieldmgphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldmgphoneKeyTyped(evt);
            }
        });

        jTextAreamgadd.setColumns(20);
        jTextAreamgadd.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextAreamgadd.setRows(5);
        jScrollPane1.setViewportView(jTextAreamgadd);

        jButtonmgedit.setBackground(new java.awt.Color(51, 153, 255));
        jButtonmgedit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonmgedit.setForeground(new java.awt.Color(153, 0, 204));
        jButtonmgedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jButtonmgedit.setText("EDIT");
        jButtonmgedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmgeditActionPerformed(evt);
            }
        });

        jButtonmgrem.setBackground(new java.awt.Color(51, 153, 255));
        jButtonmgrem.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonmgrem.setForeground(new java.awt.Color(153, 0, 204));
        jButtonmgrem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButtonmgrem.setText("REMOVE");
        jButtonmgrem.setToolTipText("");
        jButtonmgrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmgremActionPerformed(evt);
            }
        });

        jLabelmgfn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelmgfn.setForeground(new java.awt.Color(49, 23, 224));
        jLabelmgfn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmgfn.setText("First Name :");

        jTextFieldID.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jButtonmgadd1.setBackground(new java.awt.Color(51, 153, 255));
        jButtonmgadd1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonmgadd1.setForeground(new java.awt.Color(153, 0, 204));
        jButtonmgadd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButtonmgadd1.setText("ADD");
        jButtonmgadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmgadd1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Last Name", "Gender", "BirthDate", "Phone", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTextFieldsearch.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldsearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldsearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldsearchKeyTyped(evt);
            }
        });

        jLabelid1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelid1.setForeground(new java.awt.Color(49, 23, 224));
        jLabelid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelid1.setText("Id :");

        jButton1.setBackground(new java.awt.Color(175, 245, 242));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelmgln)
                            .addComponent(jLabelmggender)
                            .addComponent(jLabelmgbd)
                            .addComponent(jLabelmgphone, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelmgadd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelid1)
                            .addComponent(jLabelmgfn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jRadioButtomgnm, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(jRadioButtonmgf, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldmgphone)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jTextFieldmgfn, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldmgbd, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldmgln, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelsearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addComponent(jScrollPane2)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButtonmgadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButtonmgrem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonmgedit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(439, 439, 439)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelid1)
                            .addComponent(jLabelsearch)
                            .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldmgfn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelmgfn))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelmgln)
                            .addComponent(jTextFieldmgln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelmggender)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelmgbd)
                                    .addComponent(jTextFieldmgbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelmgphone)
                                    .addComponent(jTextFieldmgphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtomgnm)
                                    .addComponent(jRadioButtonmgf))
                                .addGap(173, 173, 173)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelmgadd))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonmgrem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonmgedit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonmgadd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldmgbdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldmgbdFocusGained
        if(jTextFieldmgbd.getText().equals("dd-mm-yyyy")){
            jTextFieldmgbd.setText("");
        }
    }//GEN-LAST:event_jTextFieldmgbdFocusGained

    private void jTextFieldmgbdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldmgbdFocusLost
        if(jTextFieldmgbd.getText().equals("")){
            jTextFieldmgbd.setText("dd-mm-yyyy");
        }
    }//GEN-LAST:event_jTextFieldmgbdFocusLost

    private void jTextFieldmgbdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldmgbdKeyTyped
        if(!(Character.isDigit(evt.getKeyChar())|| evt.getKeyChar()=='-')){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldmgbdKeyTyped

    private void jTextFieldmgphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmgphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmgphoneActionPerformed

    private void jTextFieldmgphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldmgphoneKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldmgphoneKeyTyped

    private void jButtonmgeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmgeditActionPerformed

        String fname=jTextFieldmgfn.getText();
        String lname=jTextFieldmgln.getText();
        String bdate=jTextFieldmgbd.getText();
        String phone=jTextFieldmgphone.getText();
        String address=jTextAreamgadd.getText();
         int id=Integer.valueOf(jTextFieldID.getText());
       
         String gender="Female";
       
        if(jRadioButtomgnm.isSelected()){
            gender="Male";
        }
        if(fname.equals("")||lname.equals("")|| bdate.equals("")||phone.equals("")||address.equals("")){
            JOptionPane.showMessageDialog(null, "Please Fill All Information !","Incompletet Data Error",2);
        }
        else{
            student stu=new student();
            stu.insertUpdateDeleteStudent('u',id, fname, lname, gender, bdate, phone, address);
            MainForm.jLabelstdcount.setText("Student Count : "+Integer.toString(MyFunction.countData("student")));
           try{
           ManageStudentForm.jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","First Name","Last Name","Gender","BirthDate","Phone","Address"})); 
           std.fillStudentJtable(ManageStudentForm.jTable1,"");
           }
           catch (Exception e){
               System.out.println(e.getMessage());
               
           }
        }


    }//GEN-LAST:event_jButtonmgeditActionPerformed

    private void jButtonmgremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmgremActionPerformed
       /* delete score when student is deleted 
ALTER TABLE score
ADD CONSTRAINT FK_score_student
FOREIGN KEY ('student_id')
REFERENCES student(id)
on DELETE CASCADE 
        
        */
        String fname=jTextFieldmgfn.getText();
        String lname=jTextFieldmgln.getText();
        String bdate=jTextFieldmgbd.getText();
        String phone=jTextFieldmgphone.getText();
        String address=jTextAreamgadd.getText();
         int id=Integer.valueOf(jTextFieldID.getText());
       
         String gender="Female";
       
        if(jRadioButtomgnm.isSelected()){
            gender="Male";
        }
        if(fname.equals("")||lname.equals("")|| bdate.equals("")||phone.equals("")||address.equals("")){
            JOptionPane.showMessageDialog(null, "Select  student !");
        }
        else{
            student stu=new student();
            stu.insertUpdateDeleteStudent('d',id, fname, lname, gender, bdate, phone, address);
            MainForm.jLabelstdcount.setText("Student Count : "+Integer.toString(MyFunction.countData("student")));
          try
            { ManageStudentForm.jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","First Name","Last Name","Gender","BirthDate","Phone","Address"})); 
           std.fillStudentJtable(ManageStudentForm.jTable1,"");
            }
          catch(Exception e){
              System.out.println(e.getMessage());
          }
        }

    }//GEN-LAST:event_jButtonmgremActionPerformed

    private void jRadioButtonmgfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonmgfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonmgfActionPerformed

    private void jButtonmgadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmgadd1ActionPerformed
    Addstudent student=new Addstudent();
    student.setVisible(true);
    student.pack();
    student.setLocationRelativeTo(null);
    student.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
        
    }//GEN-LAST:event_jButtonmgadd1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      int rowIndex=jTable1.getSelectedRow();
      DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
    if(model.getValueAt(rowIndex,3).toString().equals("Male")){
        jRadioButtomgnm.setSelected(true);
        jRadioButtonmgf.setSelected(false);
    }
    else{
        jRadioButtomgnm.setSelected(false);
        jRadioButtonmgf.setSelected(true);
    }
      jTextFieldID.setText(model.getValueAt(rowIndex,0).toString());
      jTextFieldmgfn.setText(model.getValueAt(rowIndex,1).toString());
      jTextFieldmgln.setText(model.getValueAt(rowIndex,2).toString());
      jTextFieldmgbd.setText(model.getValueAt(rowIndex,4).toString());
      jTextFieldmgphone.setText(model.getValueAt(rowIndex,5).toString());
      jTextAreamgadd.setText(model.getValueAt(rowIndex,6).toString());
      
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextFieldmglnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmglnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmglnActionPerformed

    private void jTextFieldsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldsearchKeyTyped
        
        
        
    }//GEN-LAST:event_jTextFieldsearchKeyTyped

    private void jTextFieldsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldsearchKeyPressed
       
    }//GEN-LAST:event_jTextFieldsearchKeyPressed

    private void jTextFieldsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldsearchKeyReleased
     jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","First Name","Last Name","Gender","BirthDate","Phone","Address"}));
        std.fillStudentJtable(jTable1, jTextFieldsearch.getText());
    }//GEN-LAST:event_jTextFieldsearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ManageStudentForm msf=new ManageStudentForm();
       this.dispose();
       msf.setVisible(true);
       msf.pack();
       msf.setLocationRelativeTo(null);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
if(evt.getKeyCode()==10){
           int rowIndex=jTable1.getSelectedRow();
      DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
    if(model.getValueAt(rowIndex,3).toString().equals("Male")){
        jRadioButtomgnm.setSelected(true);
        jRadioButtonmgf.setSelected(false);
    }
    else{
        jRadioButtomgnm.setSelected(false);
        jRadioButtonmgf.setSelected(true);
    }
      jTextFieldID.setText(model.getValueAt(rowIndex,0).toString());
      jTextFieldmgfn.setText(model.getValueAt(rowIndex,1).toString());
      jTextFieldmgln.setText(model.getValueAt(rowIndex,2).toString());
      jTextFieldmgbd.setText(model.getValueAt(rowIndex,4).toString());
      jTextFieldmgphone.setText(model.getValueAt(rowIndex,5).toString());
      jTextAreamgadd.setText(model.getValueAt(rowIndex,6).toString());
      
       }
        
        
       
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if(evt.getKeyCode()==10){
    evt.consume();
}       
    }//GEN-LAST:event_jTable1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonmgadd1;
    private javax.swing.JButton jButtonmgedit;
    private javax.swing.JButton jButtonmgrem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelid1;
    private javax.swing.JLabel jLabelmgadd;
    private javax.swing.JLabel jLabelmgbd;
    private javax.swing.JLabel jLabelmgfn;
    private javax.swing.JLabel jLabelmggender;
    private javax.swing.JLabel jLabelmgln;
    private javax.swing.JLabel jLabelmgphone;
    private javax.swing.JLabel jLabelsearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtomgnm;
    private javax.swing.JRadioButton jRadioButtonmgf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreamgadd;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldmgbd;
    private javax.swing.JTextField jTextFieldmgfn;
    private javax.swing.JTextField jTextFieldmgln;
    private javax.swing.JTextField jTextFieldmgphone;
    private javax.swing.JTextField jTextFieldsearch;
    // End of variables declaration//GEN-END:variables
}
