

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shri
 */
public class updateScore extends javax.swing.JFrame {

    /**
     * Creates new form updateScore
     */
    score sc=new score();
    DefaultTableModel model;
    public updateScore() {
        initComponents();
        sc.fillScoreJtable(jTablescores, "");
       
        
        model=(DefaultTableModel) jTablescores.getModel();
        jTablescores.setRowHeight(30);
        jTablescores.setShowGrid(true);
        jTablescores.setGridColor(Color.black);
        jTablescores.setSelectionForeground(Color.black);
        jTablescores.setSelectionBackground(Color.pink);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeladdscore = new javax.swing.JLabel();
        jLabeledscr = new javax.swing.JLabel();
        jLabeledcid = new javax.swing.JLabel();
        jButtonedadd = new javax.swing.JButton();
        jButtoneddelete = new javax.swing.JButton();
        jLabeledsid = new javax.swing.JLabel();
        jTextFieldedsid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablescores = new javax.swing.JTable();
        jTextFieldedscr = new javax.swing.JTextField();
        jLabeleddsp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaeddcp = new javax.swing.JTextArea();
        jTextFieldedcid = new javax.swing.JTextField();
        jButtonededit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(219, 247, 247));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 51), 2, true));

        jLabeladdscore.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabeladdscore.setForeground(new java.awt.Color(255, 51, 0));
        jLabeladdscore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeladdscore.setText("Edit / Delete Score");

        jLabeledscr.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabeledscr.setForeground(new java.awt.Color(49, 16, 221));
        jLabeledscr.setText("Score :");

        jLabeledcid.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabeledcid.setForeground(new java.awt.Color(49, 23, 224));
        jLabeledcid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeledcid.setText("Course Id :");

        jButtonedadd.setBackground(new java.awt.Color(46, 198, 249));
        jButtonedadd.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonedadd.setForeground(new java.awt.Color(255, 51, 0));
        jButtonedadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButtonedadd.setText("ADD");
        jButtonedadd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 2, true));
        jButtonedadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonedaddActionPerformed(evt);
            }
        });

        jButtoneddelete.setBackground(new java.awt.Color(93, 214, 255));
        jButtoneddelete.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtoneddelete.setForeground(new java.awt.Color(255, 51, 0));
        jButtoneddelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButtoneddelete.setText("Delete");
        jButtoneddelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 2, true));
        jButtoneddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneddeleteActionPerformed(evt);
            }
        });

        jLabeledsid.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabeledsid.setForeground(new java.awt.Color(49, 23, 224));
        jLabeledsid.setText("Student Id :");

        jTextFieldedsid.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 2, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTablescores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Course ID", "Score", "Description"
            }
        ));
        jTablescores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablescoresMouseClicked(evt);
            }
        });
        jTablescores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablescoresKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTablescoresKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTablescores);

        jTextFieldedscr.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldedscr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldedscrActionPerformed(evt);
            }
        });

        jLabeleddsp.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabeleddsp.setForeground(new java.awt.Color(49, 23, 224));
        jLabeleddsp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeleddsp.setText("Description :");

        jTextAreaeddcp.setColumns(20);
        jTextAreaeddcp.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextAreaeddcp.setRows(5);
        jTextAreaeddcp.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaeddcp);

        jTextFieldedcid.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        jButtonededit1.setBackground(new java.awt.Color(46, 198, 249));
        jButtonededit1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonededit1.setForeground(new java.awt.Color(255, 51, 0));
        jButtonededit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jButtonededit1.setText("EDIT");
        jButtonededit1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 2, true));
        jButtonededit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonededit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabeladdscore, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabeledcid)
                                        .addComponent(jLabeledsid, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(16, 16, 16)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldedsid, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldedcid, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabeledscr, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldedscr, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtoneddelete, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonededit1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(jButtonedadd, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabeleddsp))))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabeladdscore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeledsid)
                            .addComponent(jTextFieldedsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeledcid)
                            .addComponent(jTextFieldedcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeledscr)
                            .addComponent(jTextFieldedscr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeleddsp)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtoneddelete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonedadd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonededit1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonedaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonedaddActionPerformed
    addScoreForm addscr=new  addScoreForm();
    addscr.setVisible(true);
    addscr.pack();
    addscr.setLocationRelativeTo(null);
    addscr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
  
    }//GEN-LAST:event_jButtonedaddActionPerformed

    private void jButtoneddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneddeleteActionPerformed
       int stdId=Integer.valueOf(jTextFieldedsid.getText());
       int crsId=Integer.valueOf(jTextFieldedcid.getText());
       double scr=Double.valueOf(jTextFieldedscr.getText());
       
       sc.insertUpdateDeleteScore('d', stdId, crsId,scr,jTextAreaeddcp.getText());
       
       
       try{ updateScore.jTablescores.setModel(new DefaultTableModel(null,new Object[]{"StduentID","CourseID","Score","Description"})); 
       sc.fillScoreJtable(updateScore.jTablescores,"");}
catch(Exception e){
System.out.println(e.getMessage());
}
      
    }//GEN-LAST:event_jButtoneddeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       updateScore us=new  updateScore();
        this.dispose();
        us.setVisible(true);
        us.pack();
        us.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTablescoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablescoresMouseClicked
        int rowIndex=jTablescores.getSelectedRow();
        jTextFieldedsid.setText(jTablescores.getValueAt(rowIndex,0).toString());
       jTextFieldedcid.setText(jTablescores.getValueAt(rowIndex,1).toString());
        jTextFieldedscr.setText(jTablescores.getValueAt(rowIndex,2).toString());
        jTextAreaeddcp.setText(jTablescores.getValueAt(rowIndex,3).toString());
        
    }//GEN-LAST:event_jTablescoresMouseClicked

    private void jTablescoresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablescoresKeyPressed
        if(evt.getKeyCode()==10){
            evt.consume();
        }
    }//GEN-LAST:event_jTablescoresKeyPressed

    private void jTablescoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablescoresKeyReleased
                if(evt.getKeyCode()==10){
            int rowIndex=jTablescores.getSelectedRow();
        jTextFieldedsid.setText(jTablescores.getValueAt(rowIndex,0).toString());
       jTextFieldedcid.setText(jTablescores.getValueAt(rowIndex,1).toString());
        jTextFieldedscr.setText(jTablescores.getValueAt(rowIndex,2).toString());
        jTextAreaeddcp.setText(jTablescores.getValueAt(rowIndex,3).toString());
                    }
    }//GEN-LAST:event_jTablescoresKeyReleased

    private void jTextFieldedscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldedscrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldedscrActionPerformed

    private void jButtonededit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonededit1ActionPerformed
       int stdId=Integer.valueOf(jTextFieldedsid.getText());
       int crsId=Integer.valueOf(jTextFieldedcid.getText());
       double scr=Double.valueOf(jTextFieldedscr.getText());
       String ds=jTextAreaeddcp.getText();
       sc.insertUpdateDeleteScore('u', stdId, crsId,scr,ds);
       
       
       try{updateScore.jTablescores.setModel(new DefaultTableModel(null,new Object[]{"StudentID","CourseID","Score","Description"})); 
       sc.fillScoreJtable(updateScore.jTablescores,"");}
catch(Exception e){
System.out.println(e.getMessage());
}
       
        
    }//GEN-LAST:event_jButtonededit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateScore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonedadd;
    private javax.swing.JButton jButtoneddelete;
    private javax.swing.JButton jButtonededit1;
    private javax.swing.JLabel jLabeladdscore;
    private javax.swing.JLabel jLabeledcid;
    private javax.swing.JLabel jLabeleddsp;
    private javax.swing.JLabel jLabeledscr;
    private javax.swing.JLabel jLabeledsid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jTablescores;
    private javax.swing.JTextArea jTextAreaeddcp;
    private javax.swing.JTextField jTextFieldedcid;
    private javax.swing.JTextField jTextFieldedscr;
    private javax.swing.JTextField jTextFieldedsid;
    // End of variables declaration//GEN-END:variables
}
